### ISSUE TITLE
File upload interface and parsing

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/lili#102]

**Comment by aaronstephenson** [comment]
Just in case you want to see an example:

[File upload widget](https://github.com/USGS-WiM/CBRADMS/blob/master/src/workbench/workbench-detail.component.html#L44)
[File select event handler](https://github.com/USGS-WiM/CBRADMS/blob/master/src/workbench/workbench-detail.component.ts#L901)
[Calling the (client-side) file upload service](https://github.com/USGS-WiM/CBRADMS/blob/master/src/workbench/workbench-detail.component.ts#L950)
[Uploading the file to the server](https://github.com/USGS-WiM/CBRADMS/blob/master/src/casefiles/casefile.service.ts#L21)

**Comment by BlakeDraper** [comment]
Done with PR #142
