### ISSUE TITLE
Aliquot label printing

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/lili#104]
Need to lay out text to fit labels.

**Comment by HansVraga** [comment]
Here is how their old system dealt with labels:
>>>Sorry for the delay on printing information. Here's what I know for printing labels. Currently we print labels on these and will continue to do so: http://www.usascientific.com/Cryo-Babies-1.28x0.5-white.aspx There are 85 labels per sheet organized in 5 columns of 17 labels laid out portrait fashion on the sheet. Each label when printed contains the LIMS ID centered on one line and the collaborator ID centered on the line below it. 

Printing from LIMS involves three main things: 
1. Selecting the samples I'd like to print labels for.
2. Selecting the number of labels I'd like to print for each sample.
3. Lastly giving LIMS a number of labels to skip if I'm printing on a partial sheet. 

Labels are printed to fill a column first before moving to the next column over on the sheet. What this means is that the upper left label is considered label 1, the one right below it is label 2, the one right below that is label 3, etc... If I were to print labels for eight samples with three labels each the first sample would be labels 1,2, and 3, the second sample would be labels 4,5 and 6, etc... 

LIMS should be able to skip up to 43 labels before beginning to print. For example I if I have sheet of labels and I've already used 18 of those labels I can tell LIMS to skip 18 and it knows to start printing at label position 19. The reason I say I should be able to skip 43 labels is that's halfway on the the sheet, 2.5 columns through a sheet, and the sheets are symmetrical so I can simply rotate 180 degrees to print on the rest of the labels. Hope that makes sense. 

Currently LIMS provides a "print preview" just like a print preview on a printer of the labels to be printed so I can see exactly how LIMS is going to print the labels and where it's going to start. It looks like the current LIMS does this via PDF file. LIMS is also currently able to print more then one sheet of labels at a time. So if I were to select 35 samples and 3 labels each LIMS would know to generate 105 labels and would have no problems printing those over the two pages required.

**Comment by BlakeDraper** [comment]
Done with PR #128
