### ISSUE TITLE
Samples "All Samples" table filter by Study fail

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/lili#109]
filtering by a Study results in no samples even though there are some with the chosen study.

**Comment by troddick** [comment]
fixed by changing line 29-31 of study-filter.component.ts file to:
accepts(sample: any) {
    return (this.selectedStudy === sample.study.id);
}

**Comment by troddick** [comment]
same issue found and fixed for:
    sample-type-filter
    filter-type-filter
    sample-name-filter

**Comment by HansVraga** [comment]
@BlakeDraper Can you verify this can be closed?

**Comment by BlakeDraper** [comment]
Yes, can be closed.
