### ISSUE TITLE
May need to update the way the version is being called in from package.json

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/lili#162]
Current require statement (line 47, app.settings.ts) may cause problems in build.  See issue below and revisit:
 
> I actually managed to get this to work by simply using require('path/to/package.json') in environment.ts, which does not affect the build. It's not like using require in a component where angular needs to generate component factories through static analysis, etc. and the compiler doesn't complain.
> Since package.json is just getting required at build time, the other contents of that file shouldn't be exposed either.
> 
> Here is my environment.ts for reference:
> 
> export const environment = {
>   production: false,
>   hmr: false,
>   version: require('../../package.json').version
> };
> 

https://github.com/angular/angular-cli/issues/3770

**Comment by BlakeDraper** [comment]
Working fine.

**Comment by BillyCoda** [comment]
No longer works.

**Comment by BlakeDraper** [comment]
@BillyCoda Hi! What isn't working?
