### ISSUE TITLE
Invalid freezer locations being allowed

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/lili#180]
This is a problem both on the front end and the back end. It seems the web services and the web client are both allowing the user to submit freezer locations that do not actually exist (e.g., {freezer: 1, rack: 12, box: 1416, row: 19, spot: 1}).

I just fixed this on the back end by adding a validation. If the submitted location is invalid, the web service will respond with 400 error (Bad Request) and an appropriate message (e.g. non_field_errors": [
  "The submitted freezer location (rack: 12, box: 1416, row: 19, spot: 1) does not exist in the submitted freezer (1) whose maximum dimensions are (rack: 30, box: 16, row: 9, spot: 9).")

But it would probably be a good idea to also validate for this on the front end too and not let the user enter invalid values, and not just get a surprise 400 error (or, at least, gracefully handle the 400 error with some user feedback).

**Comment by BlakeDraper** [comment]
Yeah good call - I've been deferring this whole can of worms for further dev, but I can at least limit the range at this time.

**Comment by aaronstephenson** [comment]
Cool. You can always check for a given freezer's max dimensions, so you don't have to hard code them into the web client. `/lideservices/freezers/{id}`

**Comment by BlakeDraper** [comment]
Implemented freezer dimension lookup linkage to input max. More robust validation for later. This is a bit of a pain point for number inputs in Clarity I have discovered; so deferring until after MVP delivery.
