### ISSUE TITLE
After our big model review, TextField and CharField may not longer contain nulls

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/lili#181]
Up until our big model review, we had several "notes" or "description", etc, fields defined as CharField with null=True. But now that we have switched to TextField with just blank=True, or CharField with just blank=True (and essentially null=False), submitting nulls causes a 400 Bad Request error.

The solution is to either not submit those fields (in which case, Django will simply fill the fields with empty strings by default), or to submit those fields with empty strings ("").

Here's the list of Text and Char Fields that no longer allow nulls that still seem be getting nulls submitted:

- [ ] sample.study_site_name
- [ ] sample.technician_initials
- [ ] extractionbatch.re_extraction_notes
- [ ] reversetranscription.re_rt_notes

I think these are the only ones where you may not be submitting empty strings, but it wouldn't hurt to check all of them (see the [models file](https://github.com/USGS-WiM/lide/blob/master/lideservices/models.py) for the full list of CharField and TextField fields).

**Comment by BlakeDraper** [comment]
All of these are indeed sending strings
