### ISSUE TITLE
Change results upload field names from '_concentration' to '_gc_reaction'

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/lili#182]
Right now lili is submitting

```
{
...
"ext_neg_concentration": 0,
"rt_neg_concentration": null,
"pcr_neg_concentration": 0,
"pcr_pos_concentration": 9260,
...
}
```

but the web service endpoint is expecting

```
{
...
"ext_neg_gc_reaction": 0,
"rt_neg_gc_reaction": null,
"pcr_neg_gc_reaction": 0,
"pcr_pos_gc_reaction": 9260,
...
}
```

Please update these field names in lili, or those values will not be properly accounted for in the web service (the '_concentration' fields just get ignored by Django).

**Comment by BlakeDraper** [comment]
Fixed with PR #183
