### ISSUE TITLE
Scaffold out Admin Page

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/lili#97]
The whole content of this page is TBD, but one thing it will certainly need is a simple table for admin users to edit the lookup tables. I may suggest a grid of cards with the Clarity UI framework: https://vmware.github.io/clarity/documentation/cards but I am also open to suggestions for best flow. The idea would be to create an edit interface for all the lookup tables in the DB (list below). We may also consider making this a sub-page and leaving the top level page for other more basic admin tasks. 

- [x] units

- [x] extraction_methods

- [x] concentration_types

- [x] matrices (matrix_types)

- [x] sample_types

- [x] filter_types

- [x] control_types

- [x] targets

- [x] users (this one should probably be separate)

**Comment by aaronstephenson** [comment]
Just throwing this out there for your consideration...

There's also the Django Admin app, works right out of the box:
https://lidedev.wim.usgs.gov/admin/

Permissions are fully customizable. But it's certainly a different user experience than the lili client.

**Comment by troddick** [comment]
Are you thinking something like this:

The admin page has a card for each lookup, like so..
![image](https://user-images.githubusercontent.com/1580076/32863494-532fe748-ca21-11e7-9858-8809edeff0e6.png)

Then, the user selects a card, and they see the table containing the list of those.. like so (all mocked up using what you have, so I know the list shows Study info)
![image](https://user-images.githubusercontent.com/1580076/32863548-830bae70-ca21-11e7-9357-1affd63f1e89.png)

Then Add New will respond the way it does in your other sections, as well as edit. I could add a Delete Unit next to the edit that will delete the one they selected.

Is this what you have in mind for this?

**Comment by BlakeDraper** [comment]
I was originally thinking the table would be right there in the card since they should all be very small tables (2-3 columns each and only a handful of records for each). Then you have Add, Edit, Delete buttons in a button group at the top. Do you think there is enough space to do that, 2 cards across the top on large screens, responding down to single row on smaller? All I am saying that is different from what you are showing is you don't need to click to show the table, they are all already there.

**Comment by troddick** [comment]
Are these cards collapsible at all? What if, down the road, some get really long with lots of lookup values? Or if one card had 10 lookup values, but another had 3, then it would start to look more scattered than grid-like. Maybe I could set a max height on the cards with a auto scrollbar (throwing ideas around...) 
If the cards were collapsible, then they would all line up nicely and they could expand the one they are interested in. 
I'm all for having the functionality all right there, rather than making them click to get to another screen, esp if the content will never get too big. That will save on router logic too.

**Comment by BlakeDraper** [comment]
Oh yes I would definitely make the card uniform size. These tables will not be that big (just lookup values like types) and this will be a very infrequently used area of the app, so I am fine with table scrolling. So give the cards uniform height (width will be uniform based on the grid automatically) and it should be good.

**Comment by troddick** [comment]
I'll work on this today and get it up to the point just before POST/PUT/DELETE and then we can talk about authentication.

**Comment by troddick** [comment]
All done and ready (except for users) for testing in TR_admin branch

**Comment by BlakeDraper** [comment]
Done for now
